/**
 * FLYP ONDC — One-shot setup script
 * Reads Firebase service account JSON and generates .env automatically.
 * Usage: node scripts/setup.js /path/to/service-account-key.json
 */
const fs = require('fs');
const path = require('path');
const { generateKeyPair } = require('../src/crypto/keys');

const jsonPath = process.argv[2];

if (!jsonPath) {
  console.error('\n❌ Usage: node scripts/setup.js /path/to/service-account-key.json\n');
  process.exit(1);
}

const absPath = path.resolve(jsonPath);
if (!fs.existsSync(absPath)) {
  console.error(`\n❌ File not found: ${absPath}\n`);
  process.exit(1);
}

let sa;
try {
  sa = JSON.parse(fs.readFileSync(absPath, 'utf8'));
} catch (e) {
  console.error('\n❌ Could not parse JSON:', e.message);
  process.exit(1);
}

if (sa.type !== 'service_account') {
  console.error('\n❌ Not a service account key file.\n');
  process.exit(1);
}

const keys = generateKeyPair();
const envPath = path.join(__dirname, '..', '.env');

const privateKeyEscaped = sa.private_key.replace(/\n/g, '\\n');

const envContent = `# ============================================
# FLYP ONDC Adapter — Environment Variables
# Auto-generated by scripts/setup.js
# ============================================

# Server
PORT=3000
NODE_ENV=preprod

# ONDC Identity
SUBSCRIBER_ID=ondc.flypnow.in
SUBSCRIBER_URI=/ondc
UNIQUE_KEY_ID=flyp-key-1

# ONDC Network Endpoints (Preprod)
REGISTRY_URL=https://preprod.registry.ondc.org/ondc
GATEWAY_URL=https://preprod.gateway.ondc.org
BAP_CALLBACK_URL=https://preprod.gateway.ondc.org

# Ed25519 Keys (generated)
SIGNING_PRIVATE_KEY=${keys.privateKey}
SIGNING_PUBLIC_KEY=${keys.publicKey}
ENCRYPTION_PRIVATE_KEY=${keys.privateKey}
ENCRYPTION_PUBLIC_KEY=${keys.publicKey}

# Firebase Admin SDK
FIREBASE_PROJECT_ID=${sa.project_id}
FIREBASE_CLIENT_EMAIL=${sa.client_email}
FIREBASE_PRIVATE_KEY="${privateKeyEscaped}"

# App Config
DEFAULT_CITY_CODE=std:080
DEFAULT_COUNTRY_CODE=IND
DEFAULT_CURRENCY=INR
DEFAULT_TTL=PT30S
`;

fs.writeFileSync(envPath, envContent);

console.log('\n✅ .env file created successfully!\n');
console.log('   Firebase Project : ' + sa.project_id);
console.log('   Client Email     : ' + sa.client_email);
console.log('   Signing Pub Key  : ' + keys.publicKey);
console.log('\n📋 Save this Public Key — needed for ONDC portal → Network Settings:');
console.log('\n   SIGNING_PUBLIC_KEY=' + keys.publicKey);
console.log('\n   ENCRYPTION_PUBLIC_KEY=' + keys.publicKey);
console.log('\n🚀 Next: npm run dev  (to test locally)\n');
